### ISSUE TITLE
Thoughts?

### ISSUE THREAD

**Issue by russoreilly** [adunkman/ask#1]
From your personal site it seemed like this may be the best way to reach out to you. Given your activity in the DC NodeJS scene, I thought you might be a good person to reach out to!

Description attached.
Russ
443.221.4999
roreilly@corporatebrokers.com
[Gannett NodeJS Developer.pdf](https://github.com/adunkman/ask/files/1115571/Gannett.NodeJS.Developer.pdf)

**Comment by adunkman** [comment]
Hey @russoreilly! What’s your question? :)

**Comment by adunkman** [comment]
Closing due to lack of question — feel free to follow-up!

**Comment by russoreilly** [comment]
Hey Andrew, sorry for the delay- I was out of town for the long weekend. I'd love to chat to see if you can think of any strong data-oriented NodeJS devs that would be interested in discussing the position with Gannett/USA Today in McLean?

I'd love to connect when you have time this week.
Russ
443.221.4999

**Comment by adunkman** [comment]
No worries! Hope you had a great holiday! 

I’ve been fortunate enough to find positions through direct referrals in the past, and I’m likely to follow that path in the future. Thanks for the information, though! Cheers!

**Comment by russoreilly** [comment]
Understood, for what it’s worth this can be set up as a direct hire if that’s your preference- think of me as someone referring you directly to the hiring manager.

In the event that you’re not interested, can you think of anyone with a similar skill set that I should try reaching out to?

Thanks,
Russ O’Reilly | Business Development Executive
________________________________
(443) 221-4999 Direct
(843) 817-6385 Mobile
roreilly@corporatebrokers.com<mailto:roreilly@corporatebrokers.com>
170 Jennifer Rd. Suite 230, Annapolis, MD 21401
________________________________
[cid:A34785DC-2322-40A9-8C46-6713551C5F39]<http://www.corporatebrokers.com/>
[linked in logo]<https://www.linkedin.com/in/russoreilly>[cid:image003.png@01D13971.09EC8C00]<https://twitter.com/corporatebroker>[cid:image002.png@01D13971.09EC8C00]<https://www.facebook.com/corporatebrokers>
________________________________
