### ISSUE TITLE
Chosen Question

### ISSUE THREAD

**Issue by RedLion73** [adunkman/ask#2]
Hi.  I'm attempting to incorporate Chosen into its own Angular component.  I want to create a type-ahead/autocomplete feature where I get new values when a user types into the box and reload the options as a result.  I can successfully swap the select options on a user keydown, however, the chosen-results list doesn't update in response to the select options changing. Is there a way I can refresh that list upon updating the select options?  I realize this probably isn't the intent and may be somewhat of a hack, but this is such a perfect match for what I'm trying to accomplish that I'd like to make it work if there are no major risks.  I posted here since this isn't really a bug.  Thanks.

**Comment by adunkman** [comment]
Search the docs for “Updating Chosen Dynamically” and you’ll find your answer! Good luck!
